TDMUJudge/domserver/webapp/src/Entity/Testcase.php
<?php declare(strict_types=1);
namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;

/**
 * Stores testcases per problem
 * @ORM\Entity()
 * @ORM\Table(
 *     name="testcase",
 *     options={"collate"="utf8mb4_unicode_ci", "charset"="utf8mb4", "comment"="Stores testcases per problem"},
 *     indexes={
 *         @ORM\Index(name="probid", columns={"probid"}),
 *         @ORM\Index(name="sample", columns={"sample"})
 *     },
 *     uniqueConstraints={@ORM\UniqueConstraint(name="rank", columns={"probid","rank"})})
 */
class Testcase
{

    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", name="testcaseid", length=4,
     *     options={"comment"="Testcase ID","unsigned"=true},
     *     nullable=false)
     */
    private $testcaseid;

    /**
     * @var string
     * @ORM\Column(type="string", name="md5sum_input", length=32,
     *     options={"comment"="Checksum of input data","default"="NULL","fixed"=true},
     *     nullable=true)
     */
    private $md5sum_input;

    /**
     * @var string
     * @ORM\Column(type="string", name="md5sum_output", length=32,
     *     options={"comment"="Checksum of output data","default"="NULL","fixed"=true},
     *     nullable=true)
     */
    private $md5sum_output;

    /**
     * @var int
     * @ORM\Column(type="integer", name="probid", length=4,
     *     options={"comment"="Corresponding problem ID", "unsigned"=true},
     *     nullable=false)
     */
    private $probid;

    /**
     * @var int
     * @ORM\Column(type="integer", name="rank", length=4,
     *     options={"comment"="Determines order of the testcases in judging",
     *              "unsigned"=true},
     *     nullable=false)
     */
    private $rank;

    /**
     * @var resource
     * @ORM\Column(type="blob", length=4294967295, name="description",
     *     options={"comment"="Description of this testcase","default"="NULL"},
     *     nullable=true)
     * @Serializer\Exclude()
     */
    private $description;

    private $description_as_string = null;

    /**
     * @var string
     * @ORM\Column(type="string", name="orig_input_filename", length=255,
     *     options={"comment"="Original basename of the input file.","default"=NULL},
     *     nullable=true)
     * @Serializer\Exclude()
     */
    private $orig_input_filename;

    /**
     * @var string
     * @ORM\Column(type="string", name="image_type", length=4,
     *     options={"comment"="File type of the image and thumbnail","default"="NULL"},
     *     nullable=true)
     * @Serializer\Exclude()
     */
    private $image_type;

    /**
     * @var boolean
     * @ORM\Column(type="boolean", name="sample",
     *     options={"comment"="Sample testcases that can be shared with teams",
     *              "default"="0"},
     *     nullable=false)
     * @Serializer\Exclude()
     */
    private $sample = false;

    /**
     * @ORM\OneToMany(targetEntity="JudgingRun", mappedBy="testcase")
     * @Serializer\Exclude()
     */
    private $judging_runs;

    /**
     * @ORM\OneToMany(targetEntity="ExternalRun", mappedBy="testcase")
     * @Serializer\Exclude()
     */
    private $external_runs;

    /**
     * We use a OneToMany instead of a OneToOne here, because otherwise this
     * relation will always be loaded. See the commit message of commit
     * 9e421f96691ec67ed62767fe465a6d8751edd884 for a more elaborate explanation
     *
     * @var TestcaseContent[]|ArrayCollection
     * @ORM\OneToMany(targetEntity="TestcaseContent", mappedBy="testcase", cascade={"persist"}, orphanRemoval=true)
     * @Serializer\Exclude()
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity="Problem", inversedBy="testcases")
     * @ORM\JoinColumn(name="probid", referencedColumnName="probid", onDelete="CASCADE")
     * @Serializer\Exclude()
     */
    private $problem;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->judging_runs = new ArrayCollection();
        $this->external_runs = new ArrayCollection();
        $this->content = new ArrayCollection();
    }

    /**
     * Get testcaseid
     *
     * @return integer
     */
    public function getTestcaseid()
    {
        return $this->testcaseid;
    }

    /**
     * Set md5sumInput
     *
     * @param string $md5sumInput
     *
     * @return Testcase
     */
    public function setMd5sumInput($md5sumInput)
    {
        $this->md5sum_input = $md5sumInput;

        return $this;
    }

    /**
     * Get md5sumInput
     *
     * @return string
     */
    public function getMd5sumInput()
    {
        return $this->md5sum_input;
    }

    /**
     * Set md5sumOutput
     *
     * @param string $md5sumOutput
     *
     * @return Testcase
     */
    public function setMd5sumOutput($md5sumOutput)
    {
        $this->md5sum_output = $md5sumOutput;

        return $this;
    }

    /**
     * Get md5sumOutput
     *
     * @return string
     */
    public function getMd5sumOutput()
    {
        return $this->md5sum_output;
    }

    /**
     * Set probid
     *
     * @param integer $probid
     *
     * @return Testcase
     */
    public function setProbid($probid)
    {
        $this->probid = $probid;

        return $this;
    }

    /**
     * Get probid
     *
     * @return integer
     */
    public function getProbid()
    {
        return $this->probid;
    }

    /**
     * Set rank
     *
     * @param integer $rank
     *
     * @return Testcase
     */
    public function setRank($rank)
    {
        $this->rank = $rank;

        return $this;
    }

    /**
     * Get rank
     *
     * @return integer
     */
    public function getRank()
    {
        return $this->rank;
    }

    /**
     * Set description
     *
     * @param resource|string $description
     *
     * @return Testcase
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return resource|string|null
     */
    public function getDescription(bool $asString = false)
    {
        if ($asString && $this->description !== null) {
            if ($this->description_as_string === null) {
                $this->description_as_string = stream_get_contents($this->description);
            }
            return $this->description_as_string;
        }
        return $this->description;
    }

    /**
     * Set original input filename
     *
     * @param string $origInputFilename
     *
     * @return Testcase
     */
    public function setOrigInputFilename($origInputFilename)
    {
        $this->orig_input_filename = $origInputFilename;

        return $this;
    }

    /**
     * Get original input filename
     *
     * @return string
     */
    public function getOrigInputFilename()
    {
        return $this->orig_input_filename;
    }

    /**
     * Set imageType
     *
     * @param string $imageType
     *
     * @return Testcase
     */
    public function setImageType($imageType)
    {
        $this->image_type = $imageType;

        return $this;
    }

    /**
     * Get imageType
     *
     * @return string
     */
    public function getImageType()
    {
        return $this->image_type;
    }

    /**
     * Set sample
     *
     * @param boolean $sample
     *
     * @return Testcase
     */
    public function setSample($sample)
    {
        $this->sample = $sample;

        return $this;
    }

    /**
     * Get sample
     *
     * @return boolean
     */
    public function getSample()
    {
        return $this->sample;
    }

    /**
     * Add judgingRun
     *
     * @param \App\Entity\JudgingRun $judgingRun
     *
     * @return Testcase
     */
    public function addJudgingRun(\App\Entity\JudgingRun $judgingRun)
    {
        $this->judging_runs[] = $judgingRun;

        return $this;
    }

    /**
     * Remove judgingRun
     *
     * @param \App\Entity\JudgingRun $judgingRun
     */
    public function removeJudgingRun(\App\Entity\JudgingRun $judgingRun)
    {
        $this->judging_runs->removeElement($judgingRun);
    }

    /**
     * Get judgingRuns
     *
     * @return Collection
     */
    public function getJudgingRuns()
    {
        return $this->judging_runs;
    }

    /**
     * Gets the first judging run for this testcase.
     *
     * This is useful when this testcase is joined to a single run to get code completion in Twig templates
     *
     * @return JudgingRun|null
     */
    public function getFirstJudgingRun()
    {
        return $this->judging_runs->first() ?: null;
    }

    /**
     * Gets the first external run for this testcase.
     *
     * This is useful when this testcase is joined to a single external run to get code completion in Twig templates
     *
     * @return ExternalRun|null
     */
    public function getFirstExternalRun()
    {
        return $this->external_runs->first() ?: null;
    }

    /**
     * Set content
     *
     * @param TestcaseContent $content
     *
     * @return Testcase
     */
    public function setContent(?TestcaseContent $content)
    {
        $this->content->clear();
        $this->content->add($content);
        $content->setTestcase($this);

        return $this;
    }

    /**
     * Get content
     *
     * @return TestcaseContent
     */
    public function getContent(): ?TestcaseContent
    {
        return $this->content->first() ?: null;
    }

    /**
     * Set problem
     *
     * @param \App\Entity\Problem $problem
     *
     * @return Testcase
     */
    public function setProblem(\App\Entity\Problem $problem = null)
    {
        $this->problem = $problem;

        return $this;
    }

    /**
     * Get problem
     *
     * @return \App\Entity\Problem
     */

TDMUJudge/domserver/webapp/src/Controller/Jury/AuditLogController.php
<?php declare(strict_types=1);

namespace App\Controller\Jury;

use App\Entity\AuditLog;
use App\Entity\Testcase;
use App\Entity\User;
use App\Service\DOMJudgeService;
use App\Service\EventLogService;
use App\Utils\Utils;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Asset\Packages;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/jury/auditlog")
 * @IsGranted("ROLE_ADMIN")
 */
class AuditLogController extends AbstractController
{
    /**
     * @var EntityManagerInterface
     */
    protected $em;

    /**
     * @var DOMJudgeService
     */
    protected $dj;

    /**
     * @var EventLogService
     */
    protected $eventLogService;

    /**
     * AuditLogController constructor.
     * @param EntityManagerInterface $em
     * @param DOMJudgeService        $dj
     * @param EventLogService        $eventLogService
     */
    public function __construct(
        EntityManagerInterface $em,
        DOMJudgeService $dj,
        EventLogService $eventLogService
    ) {
        $this->em              = $em;
        $this->dj              = $dj;
        $this->eventLogService = $eventLogService;
    }

    /**
     * @Route("", name="jury_auditlog")
     */
    public function indexAction(Request $request, Packages $assetPackage, KernelInterface $kernel)
    {
        $timeFormat = (string)$this->dj->dbconfig_get('time_format', '%H:%M');

        $showAll = $request->query->get('showAll', false);
        $page = $request->query->get('page', 1);
        $limit = 1000;

        $em = $this->em;
        $query = $em->createQueryBuilder()
                    ->select('a')
                    ->from(AuditLog::class, 'a')
                    ->orderBy('a.logid', 'DESC');

        $paginator = new Paginator($query);
        if ($showAll) {
            $paginator->getQuery();
        } else {
            $paginator->getQuery()
                      ->setFirstResult($limit * ($page - 1))
                      ->setMaxResults($limit);
        }
        $auditlog_table= [];
        foreach($paginator as $logline) {

            $data = [];
            $data['id']['value'] = $logline->getLogId();

            $time = $logline->getLogTime();
            $data['when']['value'] = Utils::printtime($time, $timeFormat);
            $data['when']['title'] = Utils::printtime($time, "%Y-%m-%d %H:%M:%S (%Z)");
            $data['when']['sortvalue'] = $time;

            $data['who']['value'] = $logline->getUser();

            $datatype = $logline->getDatatype();
            $dataid = $logline->getDataId();
            $data['what']['value'] = $datatype . " " . $dataid . " " .
                            $logline->getAction() . " " .
                            $logline->getExtraInfo();
            if( !is_null($dataid) ) {
                $dataurl = $this->generateDatatypeUrl($datatype, $dataid);
            }
            if (isset($dataurl)) {
                $data['what']['link'] = $dataurl;
            }

            $cid = $logline->getCid();
            if ( $cid ) {
                    $data['where']['value'] = "c" . $cid;
                    $data['where']['sortvalue'] = $cid;
                    $data['where']['link'] = $this->generateUrl('jury_contest', ['contestId' => $cid]);
            } else {
                    $data['where']['value'] = '';
            }

            $auditlog_table[] = [ 'data' => $data, 'actions' => [] ];
        }
        $table_fields = [
            'id' => ['title' => 'ID', 'sort' => false],
            'when' => ['title' => 'time', 'sort' => false],
            'who' => ['title' => 'user', 'sort' => false],
            'where' => ['title' => 'contest', 'sort' => false],
            'what' => ['title' => 'action', 'sort' => false],
        ];

        $maxPages = ceil($paginator->count() / $limit);
        $thisPage = $page;

        return $this->render('jury/auditlog.html.twig', [
            'auditlog' => $auditlog_table,
            'table_fields' => $table_fields,
            'table_options' => ['ordering' => 'false', 'searching' => 'false'],
            'maxPages' => $maxPages,
            'thisPage' => $thisPage,
            'showAll' => $showAll,
        ]);
    }

    private function generateDatatypeUrl(string $type, $id)
    {
        switch ($type) {
            case 'balloon':
                return $this->generateUrl('jury_balloons');
            case 'clarification':
                return $this->generateUrl('jury_clarification', ['id' => $id]);
            case 'configuration':
                return $this->generateUrl('jury_config');
            case 'contest':
                return $this->generateUrl('jury_contest', ['contestId' => $id]);
            case 'executable':
                return $this->generateUrl('jury_executable', ['execId' => $id]);
            case 'internal_error':
                return $this->generateUrl('jury_internal_error', ['errorId' => $id]);
            case 'judgehost':
                return $this->generateUrl('jury_judgehost', ['hostname' => $id]);
            case 'judgehosts':
                return $this->generateUrl('jury_judgehosts');
            case 'judgehost_restriction':
                return $this->generateUrl('jury_judgehost_restriction', ['restrictionId' => $id]);
            case 'judging':
                return $this->generateUrl('jury_submission_by_judging', ['jid' => $id]);
            case 'language':
                return $this->generateUrl('jury_language', ['langId' => $id]);
            case 'problem':
                return $this->generateUrl('jury_problem', ['probId' => $id]);
            case 'submission':
                return $this->generateUrl('jury_submission', ['submitId' => $id]);
            case 'team':
                return $this->generateUrl('jury_team', ['teamId' => $id]);
            case 'team_affiliation':
                return $this->generateUrl('jury_team_affiliation', ['affilId' => $id]);
            case 'team_category':
                return $this->generateUrl('jury_team_category', ['categoryId' => $id]);
            case 'user':
                // Pre 6.1, usernames were stored instead of numeric ids
                if (!is_numeric($id)) {
                    $user = $this->em->getRepository(User::class)->findOneBy(['username'=>$id]);
                    $id = $user->getUserId();
                }
                return $this->generateUrl('jury_user', ['userId' => $id]);
            case 'testcase':
                $testcase = $this->em->getRepository(Testcase::class)->find($id);
                if ($testcase) {
                    return $this->generateUrl('jury_problem_testcases', ['probId' => $testcase->getProbid()]);
                }
                break;
        }
        return null;
    }
}

TDMUJudge/domserver/webapp/templates/jury/partials/analysis_filter.html.twig
Filter:
<div class="btn-group btn-group-toggle btn-group-sm mb-3" data-toggle="buttons">
    {%- for key, label in filters %}

        <label class="btn btn-secondary {% if key == view %}active{% endif %}">
            <input type="radio" name="viewtype" autocomplete="off" value="{{ key }}"
                   {% if key == view %}checked{% endif %}> {{ label }}
        </label>
    {%- endfor %}
</div>

<script>
    $(function () {
        $('input[name=viewtype]').on('change', function () {
            window.location = '?view=' + $(this).val();
        });
    });
</script>

TDMUJudge/domserver/webapp/templates/jury/partials/judgehost_list.html.twig
{% import "jury/jury_macros.twig" as macros %}
{{ macros.table(judgehosts, table_fields, num_actions, {ordering: 'false'}) }}

TDMUJudge/domserver/webapp/templates/jury/partials/judgehosts_form.html.twig
{{ form_start(form) }}

<table class="table table-sm table-striped">
    <thead>
    <tr>
        <th>{{ form_label(form.judgehosts.vars.prototype.hostname) }}</th>
        <th>{{ form_label(form.judgehosts.vars.prototype.active) }}</th>
        <th>{{ form_label(form.judgehosts.vars.prototype.restriction) }}</th>
    </tr>
    </thead>
    <tbody data-collection-holder>
    {% for judgehost in form.judgehosts %}
        <tr>
            <td style="width: 20%">
                {{ form_widget(judgehost.hostname) }}
            </td>
            <td style="width: 10%">
                {{ form_widget(judgehost.active) }}
                {{ form_errors(judgehost.active) }}
            </td>
            <td>
                {{ form_widget(judgehost.restriction) }}
                {{ form_errors(judgehost.restriction) }}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{{ form_widget(form.save) }}

{{ form_end(form) }}

TDMUJudge/domserver/webapp/templates/jury/partials/language_form.html.twig
<div class="row">
    <div class="col-lg-8">
        {{ form_start(form) }}
        {% if form.offsetExists('langid') %}
            {{ form_row(form.langid) }}
        {% endif %}
        {% if form.offsetExists('externalid') %}
            {{ form_row(form.externalid) }}
        {% endif %}
        {{ form_row(form.name) }}
        {{ form_row(form.requireEntryPoint) }}
        {{ form_row(form.entryPointDescription) }}
        {{ form_row(form.allowSubmit) }}
        {{ form_row(form.allowJudge) }}
        <div class="form-group">
            {{ form_label(form.timeFactor) }}
            <div class="input-group">
                {{ form_widget(form.timeFactor) }}
                <div class="input-group-append">
                    <div class="input-group-text">&times;</div>
                </div>
            </div>
        </div>
        {{ form_row(form.compileExecutable) }}
        {{ form_row(form.extensions) }}
        {{ form_row(form.filterCompilerFiles) }}
        {{ form_end(form) }}
    </div>
</div>

<script>
    var $extensionsHolder;
    var $addExtensionButton = $('<button type="button" class="btn btn-secondary"><i class="fas fa-plus"></i></button>');

    $(function () {
        $extensionsHolder = $('div#language_extensions');
        $extensionsHolder.append($addExtensionButton);

        $extensionsHolder.data('index', $extensionsHolder.find(':input').length);

        $addExtensionButton.on('click', function (e) {
            addExtension($extensionsHolder, $addExtensionButton);
        });

        $extensionsHolder.find('div.form-group').each(function() {
            addDeleteLink($(this));
        });

        function addExtension($extensionsHolder, $addExtensionButton) {
            var prototype = $extensionsHolder.data('prototype');
            var index = $extensionsHolder.data('index');
            var newForm = prototype;
            newForm = newForm.replace(/__name__/g, index);
            $extensionsHolder.data('index', index + 1);
            var $newForm = $(newForm);
            $addExtensionButton.before($newForm);
            addDeleteLink($newForm);
        }

        function addDeleteLink($extensionDiv) {
            var $removeFormButton = $('<button type="button" class="input-group-append btn btn-danger"><i class="fas fa-trash"></i></button>');
            var $inputGroup = $('<div class="input-group"></div>');
            var $formControl = $extensionDiv.find('.form-control');
            $inputGroup.append($formControl);
            $inputGroup.append($removeFormButton);
            $extensionDiv.html($inputGroup);

            $removeFormButton.on('click', function(e) {
                $extensionDiv.remove();
            });
        }
    });
</script>

TDMUJudge/domserver/webapp/templates/jury/partials/problem_form.html.twig
<div class="row">
    <div class="col-lg-8">
        {{ form_start(form) }}
        {% if form.offsetExists('externalid') %}
            {{ form_row(form.externalid) }}
        {% endif %}
        {{ form_row(form.name) }}
        <div class="form-group">
            {{ form_label(form.timelimit) }}
            <div class="input-group">
                {{ form_widget(form.timelimit) }}
                <div class="input-group-append">
                    <div class="input-group-text">sec</div>
                </div>
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.memlimit) }}
            <div class="input-group">
                {{ form_widget(form.memlimit) }}
                <div class="input-group-append">
                    <div class="input-group-text">kB</div>
                </div>
            </div>
            {{ form_help(form.memlimit) }}
        </div>
        <div class="form-group">
            {{ form_label(form.outputlimit) }}
            <div class="input-group">
                {{ form_widget(form.outputlimit) }}
                <div class="input-group-append">
                    <div class="input-group-text">kB</div>
                </div>
            </div>
            {{ form_help(form.outputlimit) }}
        </div>
        {{ form_end(form) }}
    </div>
</div>

TDMUJudge/domserver/webapp/templates/jury/partials/rejudging_submissions.html.twig
{% if ajax is defined and ajax %}
    <span class="d-none" data-new-todo>
        {{ todo }}
    </span>
    <div class="d-none" data-new-rejudging-buttons>
        {% include 'jury/partials/rejudging_buttons.html.twig' %}
    </div>
    <div class="d-none" data-new-rejudging-matrix>
        {% include 'jury/partials/rejudging_matrix.html.twig' %}
    </div>
{% endif %}

{%- include 'jury/partials/submission_list.html.twig' with {showContest: true} %}

TDMUJudge/domserver/webapp/templates/jury/partials/shadow_submissions.html.twig
{% if ajax is defined and ajax %}
    <div class="d-none" data-new-shadow-matrix>
        {% include 'jury/partials/shadow_matrix.html.twig' %}
    </div>
{% endif %}

{%- include 'jury/partials/submission_list.html.twig' %}

TDMUJudge/domserver/webapp/templates/jury/partials/submission_graph.html.twig
{% set timelimit = submission.problem.timelimit * submission.language.timeFactor %}
<div>
    {% if selectedJudging is not null %}
        <div style="display: inline-block" id="testcaseruntime">
            <h3 id="graphs">Testcase Runtimes</h3>
            <svg style="width:500px; height:250px;"></svg>
        </div>
    {% endif %}
    {% if externalJudgement is not null and externalJudgement.result is not null %}
        <div style="display: inline-block" id="externalruntime">
            <h3 id="graphs">External Testcase Runtimes</h3>
            <svg style="width:500px; height:250px;"></svg>
        </div>
    {% endif %}
    {% if judgings|length > 1 %}
        <div style="display: inline-block" id="maxruntime">
            <h3 id="graphs">Max Runtimes</h3>
            <svg style="width:500px; height:250px;"></svg>
        </div>
    {% endif %}
</div>

<script>
    {% set colors = {
        'correct':        '#28a745',
        'wrong-answer':   '#dc3545',
        'timelimit':      'orange',
        'run-error':      '#ff3399',
        'compiler-error': 'grey',
        'no-output':      'purple',
        'frozen':         'blue',
        'output-limit':   'black',
    } %}
    function create_chart(data, maxY) {
        var tickStep = 1;
        if (maxY <= 2) {
            tickStep = 0.2;
        } else if (maxY <= 5) {
            tickStep = 0.5;
        }
        maxY += tickStep;
        var chart = nv.models.multiBarChart()
            .x(function (d) {
                return d.label
            })
            .y(function (d) {
                return d.value
            })
            .showControls(false)
            .reduceXTicks(true)
            .forceY([0, maxY])
            .duration(250)
            .showLegend(false)
        ;
        var tickValues = [];
        for (i = 0; i <= maxY; i += tickStep) {
            tickValues.push(i);
        }
        chart.yAxis
            .tickValues(tickValues)
            .axisLabel('Runtime(in s)');
        return chart;
    }

    $(function () {
        var maxY = {{ timelimit }};
        {% for judging in judgings %}
        maxY = Math.max(maxY, {{ maxRunTimes[judging.judgingId]|default(0) }});
        {% endfor %}
        {% if judgings|length > 1 %}
        var run_max_times = [
            {
                key: "Max Runtime",
                values: [
                    {% for judging in judgings | filter(judging => judging.result) %}
                    {
                        "label": "j{{ judging.judgingid }}",
                        "value": {{ maxRunTimes[judging.judgingId]|default(0) }},
                        "color": "{{ colors[judging.result] }}",
                    },
                    {% endfor %}
                ]
            }
        ];
        nv.addGraph(function () {
            var chart = create_chart(run_max_times, maxY);
            chart.xAxis.axisLabel("Judging");
            d3.select('#maxruntime svg')
                .datum(run_max_times)
                .call(chart);
            var svgsize = chart.container.clientWidth || chart.container.parentNode.clientWidth;
            var line = d3.select('#maxruntime svg')
                .append('line')
                .attr({
                    x1: chart.margin().left,
                    y1: chart.yAxis.scale()({{ timelimit }}) + chart.margin().top,
                    x2: +svgsize - chart.margin().right,
                    y2: chart.yAxis.scale()({{ timelimit }}) + chart.margin().top,
                })
                .style("stroke", "#F00");
            nv.utils.windowResize(chart.update);
            return chart;
        });
        {% endif %}

        {% if selectedJudging is not null %}
        var testcase_times = [
            {
                key: "Runtime",
                values: [
                    {% for run in runs %}
                    {
                        "label": "{{ run.rank }}",
                        "value": {% if run.firstJudgingRun %}{{ run.firstJudgingRun.runtime|default(0) }}{% else %}0{% endif %},
                        "color": "{% if run.firstJudgingRun %}{{ colors[run.firstJudgingRun.runresult]|default('grey') }}{% else %}grey{% endif %}",
                        "description": "{{ run.description(true)|default(run.rank) }}",
                    },
                    {% endfor %}
                ]
            }
        ];
        nv.addGraph(function () {
            var chart = create_chart(testcase_times, maxY);
            chart.tooltip.contentGenerator(function (obj) {
                var format = d3.format(".3f");
                return "<b>Testcase " + obj.data.description + "</b><br><b>Runtime:</b> " + format(obj.data.value) + "s";
            });
            chart.xAxis.axisLabel("Testcase Rank");
            d3.select('#testcaseruntime svg')
                .datum(testcase_times)
                .call(chart);
            var svgsize = chart.container.clientWidth || chart.container.parentNode.clientWidth;
            var line = d3.select('#testcaseruntime svg')
                .append('line')
                .attr({
                    x1: chart.margin().left,
                    y1: chart.yAxis.scale()({{ timelimit }}) + chart.margin().top,
                    x2: +svgsize - chart.margin().right,
                    y2: chart.yAxis.scale()({{ timelimit }}) + chart.margin().top,
                })
                .style("stroke", "#F00");
            nv.utils.windowResize(chart.update);
            return chart;
        });
        {% endif %}

        {# TODO: merge this in the above graph? #}
        {% if externalJudgement is not null and externalJudgement.result is not null %}
        var external_times = [
            {
                key: "Runtime",
                values: [
                    {% for run in externalRuns %}
                    {
                        "label": "{{ run.rank }}",
                        "value": {% if run.firstExternalRun %}{{ run.firstExternalRun.runtime|default(0) }}{% else %}0{% endif %},
                        "color": "{% if run.firstExternalRun %}{{ colors[run.firstExternalRun.result]|default('grey') }}{% else %}grey{% endif %}",
                        "description": "{{ run.description|default(run.rank) }}",
                    },
                    {% endfor %}
                ]
            }
        ];
        nv.addGraph(function () {
            var chart = create_chart(external_times, maxY);
            chart.tooltip.contentGenerator(function (obj) {
                var format = d3.format(".3f");
                return "<b>Testcase " + obj.data.description + "</b><br><b>Runtime:</b> " + format(obj.data.value) + "s";
            });
            chart.xAxis.axisLabel("Testcase Rank");
            d3.select('#externalruntime svg')
                .datum(external_times)
                .call(chart);
            var svgsize = chart.container.clientWidth || chart.container.parentNode.clientWidth;
            var line = d3.select('#externalruntime svg')
                .append('line')
                .attr({
                    x1: chart.margin().left,
                    y1: chart.yAxis.scale()({{ timelimit }}) + chart.margin().top,
                    x2: +svgsize - chart.margin().right,
                    y2: chart.yAxis.scale()({{ timelimit }}) + chart.margin().top,
                })
                .style("stroke", "#F00");
            nv.utils.windowResize(chart.update);
            return chart;
        });
        {% endif %}
    })
</script>

{% include 'jury/analysis/download_graphs.html.twig' %}